### PR TITLE
The better guide

### PR DESCRIPTION
**Pull request by zackprogrammer**
This is the better guide.

### CODE REVIEW

**Comment by HugoTro** [comment]
Can you please stop using u as you?

**Comment by zackprogrammer** [comment]
yeah. Il do my best as grammer. I hope i dont have to rewrite the entire thing. il ask dynamic to replace the u with you.

**Comment by HugoTro** [comment]
There is still some ur and overall it seems like you are talking to a friend like "bc I don't feel like downloading rn" <-- you don't write that in a guide

**Comment by Dynamic6448** [comment]
what he said ^

**Comment by zackprogrammer** [comment]
Ok i did that.

**Comment by zackprogrammer** [comment]
I added like 6 more commits can u see them plz.

**Comment by zackprogrammer** [comment]
at this point i would wish that someone could actually fix my grammer lol.

**Comment by Dynamic6448** [comment]
there is still 5 u/ur

**Comment by zackprogrammer** [comment]
ok fine but next time can u fix grammer plz.

**Pull request closed without merging**
